services:
  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    container_name: nginx
    restart: unless-stopped
    networks: 
      - net-docker
    volumes:
      - /home/sbienias/data/v-wordprs:/var/www/html
    ports: 
      - 443:443
    links:
      - wordpress
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    networks:
      - net-docker
    volumes:
      -  /home/sbienias/data/v-db:/var/lib/mysql:rw
    env_file:
      - .env
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    depends_on: 
      - mariadb
    networks:
      - net-docker
    volumes:
      -  /home/sbienias/data/v-wordprs:/var/www/html
    env_file:
      - .env
networks:
  net-docker:
    driver: bridge
    name: Docker_network
volumes:
  v-db:
    name: v-db
    driver: local
    driver_opts:
      type: auto
      o: bind
      device: /home/sbienias/data/v-db
  v-wordprs:
    name: v-wordprs
    driver: local
    driver_opts:
      type: auto
      o: bind
      device: /home/sbienias/data/v-wordprs