services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: unless-stopped
    networks: 
      - doc-net
    volumes:
      - /home/sbienias/data:/data:rw
    ports: 
      - "443:443"
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    networks:
      - doc-net
    volumes:
      - /home/sbienias/data:/data:rw
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    depends_on: 
      - mariadb
    networks: 
      - doc-net
    volumes:
      - /home/sbienias/data:/data:rw
networks:
  doc-net: