services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: unless-stopped
    networks: 
      - docker-network
    volumes:
      - wordprs:/data/wordpress:rw
    ports: 
      - "443:443"
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    networks:
      - docker-network
    volumes:
      - db:/data/db:rw
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    ports:
      - "8000:80"
    restart: unless-stopped
    depends_on: 
      - mariadb
    networks: 
      - docker-network
    volumes:
      - wordprs:/data/wordpress:rw
networks:
  docker-network: {}
volumes:
  db:
    # external: true
  wordprs:
    # external: true