USE mysql;

CREATE USER IF NOT EXISTS 'WP_ID'@'%' IDENTIFIED BY 'WP_PW';
CREATE DATABASE IF NOT EXISTS WP_DB_NAME;
GRANT ALL PRIVILEGES ON WP_DB_NAME.* TO 'WP_ID'@'%';

FLUSH PRIVILEGES;

DELETE FROM mysql.user WHERE User='';

DROP DATABASE IF EXISTS test;
DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%';

ALTER USER 'root'@'localhost' IDENTIFIED BY 'MYSQL_ROOT_PASSWORD';

FLUSH PRIVILEGES;
